name: Check Ruby Style and Vulnerabilities

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop-bundler-audit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker version
        run: docker --version

      - name: docker-compose version
        run: docker-compose --version

      - name: pull
        run: docker-compose -f docker-compose.yml -f docker-compose.checks.yml pull

      - name: Run Checks
        run: docker-compose -f docker-compose.yml -f docker-compose.checks.yml up
