name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  default-chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker version
        run: docker --version

      - name: docker-compose version
        run: docker-compose --version

      - name: docker-compose pull
        run: docker-compose -f docker-compose.yml -f docker-compose.seleniumchrome.yml pull

      - name: Run Selenium Chrome
        run: docker-compose -f docker-compose.yml -f docker-compose.seleniumchrome.yml run -d seleniumchrome

      - name: Run Tests
        run: docker-compose -f docker-compose.yml -f docker-compose.seleniumchrome.yml run browsertests

  firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker version
        run: docker --version

      - name: docker-compose version
        run: docker-compose --version

      - name: pull
        run: docker-compose -f docker-compose.yml -f docker-compose.seleniumfirefox.yml pull

      - name: Run Selenium Firefox
        run: docker-compose -f docker-compose.yml -f docker-compose.seleniumfirefox.yml run -d seleniumfirefox

      - name: Run Tests
        run: docker-compose -f docker-compose.yml -f docker-compose.seleniumfirefox.yml run browsertests
